#!/bin/bash
mode: 'train'
use_cuda: 1 # 1 for True, 0 for False

sampling_rate: 48000
network: "DCCRN_SE_48K"  ##network type
## FFT Parameters
win_type: hanning
win_len: 960
win_inc: 480
fft_len: 1024

# Train
tr_list: 'data/tr_demand_28_spks_16k.scp'
cv_list: 'data/cv_demand_testset_16k.scp'
init_learning_rate: 0.0001 #learning rate for a new training
finetune_learning_rate: 0.0001 #learning rate for a finetune training
max_epoch: 20

weight_decay: 0.00001
clip_grad_norm: 10.

# Log
seed: 777

# # dataset
num_workers: 4
batch_size: 8
accu_grad: 1  # accumulate multiple batch sizes for one back-propagation updating
effec_batch_size: 12   # per GPU, only used if accu_grad is set to 1, must be multiple times of batch size
max_length: 3         # truncate the utterances in dataloader, in seconds

