#!/bin/bash
mode: 'inference'
use_cuda: 1 # 1 for True, 0 for False
num_gpu: 1
sampling_rate: 48000
network: "DCCRN_SE_16K"  ##network type
checkpoint_dir: "checkpoints/DCCRN_SE_48K"

input_path: "data/cv_demand_testset_16k.scp"  # an input dir or input scp file
output_dir: "outputs/DCCRN_SE_48K" ## output dir to store processed audio

# decode parameters
one_time_decode_length: 3 #maximum segment length for one-pass decoding (seconds), longer audio  will use segmented decoding
decode_window: 3 #one-pass decoding length

# FFT parameters
win_type: 'hanning'
win_len: 960
win_inc: 480
fft_len: 1024
max_length: 3